### ISSUE TITLE
Automate Image sync from quay to internal registry and create mirrors

### ISSUE THREAD

**Issue by krsacme** [dci-labs/example-cnf-config#19]
The images in quay registry has to be manually uploaded (though the scripts are available, the trigger is manual). And individual catalog index images are created for each cluster which can be avoided by creating mirror entries (refer to bundles.sh script in folder "~/skramaja/" of jumphost). Automate this step with the so that manual efforts removed.

**Comment by tonyskapunk** [comment]
I think we have automated this already :smiley:  all the operators (testpmd, trex, testpmd-lb and cnf-app-mac-operator) are automatically updated when a new tag is created.
